trigger:
  batch: true
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

variables:
  RepoName: demo-1
  SolutionFile: demo-1.sln

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: Build
      displayName: Build Job
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '6.0.x'

        - script: |
            workspace="$(WorkspacePath)"
            solution="$(SolutionFile)"
            echo "Restoring: $workspace/$solution"
            dotnet restore "$workspace/$solution"
            dotnet build "$workspace/$solution" --no-restore --configuration Release
          displayName: 'Restore and Build'

        - script: |
            dotnet test $(SolutionFile) --no-build --configuration Release --logger trx
          displayName: 'Run Tests'
