trigger:
  batch: true
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

variables:
  RepoName: demo_1
  SolutionFile: demo_1.sln

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: Build
      displayName: Build Job
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '6.0.x'

        - script: |
            dotnet restore test1.sln
            dotnet build test1.sln --no-restore --configuration Release
          displayName: 'Restore and Build'

        - script: |
            dotnet test $(SolutionFile) --no-build --configuration Release --logger trx
          displayName: 'Run Tests'
