trigger:
  batch: true
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

variables:
  RepoName: demo_21
  SolutionFile: demo_21.sln
  WorkspacePath: /tmp/34c9a3ba-a619-4a95-aa56-dbeaae4fd60b

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: Build
      displayName: Build Job
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '6.0.x'

        - script: |
            echo "RepoName is: $(RepoName)"
            echo "SolutionFile is: $(SolutionFile)"
            echo "WorkspacePath is: $(WorkspacePath)"
          displayName: 'Print Variables'

        - script: |
            echo "Restoring and building the solution.../$(SolutionFile)"
            dotnet restore $(RepoName)/$(SolutionFile)
            dotnet build $(RepoName)/$(SolutionFile) --no-restore --configuration Release
          displayName: 'Restore and Build'

        - script: |
            dotnet test $(RepoName)/$(SolutionFile) --no-build --configuration Release --logger trx
          displayName: 'Run Tests'
