trigger:
  batch: true
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

variables:
  RepoName: demo_15
  SolutionFile: demo_15.sln
  WorkspacePath: C:\Users\SUKHCH~1.K\AppData\Local\Temp\dd335b4f-e81b-4b35-bec3-bf1fddde7394

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: Build
      displayName: Build Job
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '6.0.x'

        - script: |
            echo "RepoName is: $(RepoName)"
            echo "SolutionFile is: $(SolutionFile)"
            echo "WorkspacePath is: $(WorkspacePath)"
          displayName: 'Print Variables'

        - script: |
            dotnet restore $(RepoName)/$(SolutionFile)
            dotnet build $(RepoName)/$(SolutionFile) --no-restore --configuration Release
          displayName: 'Restore and Build'

        - script: |
            dotnet test $(RepoName)/$(SolutionFile) --no-build --configuration Release --logger trx
          displayName: 'Run Tests'
