trigger:
  batch: true
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

variables:
  RepoName: demo-13
  SolutionFile: demo-13.sln
  WorkspacePath: C:\Users\SUKHCH~1.K\AppData\Local\Temp\69b06ec2-c80b-4240-8168-665a2da0d0b0

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: Build
      displayName: Build Job
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '6.0.x'

        - script: |
            echo "RepoName is: $(RepoName)"
            echo "SolutionFile is: $(SolutionFile)"
            echo "WorkspacePath is: $(WorkspacePath)"
          displayName: 'Print Variables'

        - script: |
            dotnet restore $(WorkspacePath)/$(SolutionFile)
            dotnet build $(WorkspacePath)/$(SolutionFile) --no-restore --configuration Release
          displayName: 'Restore and Build'

        - script: |
            dotnet test $(WorkspacePath)/$(SolutionFile) --no-build --configuration Release --logger trx
          displayName: 'Run Tests'
