trigger:
  batch: true
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

variables:
  RepoName: demo-8
  SolutionFile: demo-8.sln

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: Build
      displayName: Build Job
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '6.0.x'

        - script: |
            echo "RepoName is: "
            echo "SolutionFile is: "

        - script: |
            dotnet restore $(SolutionFile)
            dotnet build $(SolutionFile) --no-restore --configuration Release
          displayName: 'Restore and Build'

        - script: |
            dotnet test $(SolutionFile) --no-build --configuration Release --logger trx
          displayName: 'Run Tests'
