trigger:
  batch: true
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

variables:
  RepoName: demo-16
  SolutionFile: demo-16.sln
  WorkspacePath: C:\Users\SUKHCH~1.K\AppData\Local\Temp\35f7ae96-927a-4589-929a-6403ebb290e3

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: Build
      displayName: Build Job
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '6.0.x'

        - script: |
            echo "RepoName is: $(RepoName)"
            echo "SolutionFile is: $(SolutionFile)"
            echo "WorkspacePath is: $(WorkspacePath)"
          displayName: 'Print Variables'

        - script: |
            dotnet restore $(RepoName)/$(SolutionFile)
          displayName: 'Restore and Build'

        - script: |
            dotnet test $(RepoName)/$(SolutionFile) --no-build --configuration Release --logger trx
          displayName: 'Run Tests'
